In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('strava_activity.csv')

In [4]:
data_males = data[data['athlete.sex'] == "M"]
data_females = data[data['athlete.sex'] == "F"]

In [6]:
data_males

,achievement_count,athlete.badge_type_id,athlete.city,athlete.country,athlete.premium,athlete.resource_state,athlete.sex,athlete.state,athlete_count,average_cadence,...,start_latlng,start_longitude,suffer_score,timezone,total_elevation_gain,total_photo_count,trainer,type,weighted_average_watts,workout_type
1,0,0,Oisterwijk,The Netherlands,0,2,M,NB,1,NaN,...,[38.68 0.09],0.09,NaN,(GMT+01:00) Europe/Madrid,456.9,0,0,Ride,NaN,0.0
2,8,0,Ypsilanti,United States,0,2,M,MI,2,NaN,...,[42.42 -83.96],-83.96,NaN,(GMT-05:00) America/Detroit,292.2,0,0,Ride,NaN,NaN
5,0,0,Cardiff,United Kingdom,0,2,M,Wales,1,NaN,...,[51.53 -3.1],-3.10,NaN,(GMT+00:00) Europe/London,81.4,0,0,Ride,NaN,0.0
6,0,0,Šiauliai,Lithuania,0,2,M,Šiauliai County,1,NaN,...,[55.85 23.13],23.13,NaN,(GMT+02:00) Europe/Vilnius,303.0,0,0,Ride,NaN,NaN
10,5,1,West Kilbride,United Kingdom,1,2,M,Scotland,3,79.1,...,[55.64 -4.53],-4.53,55.0,(GMT+00:00) Europe/London,301.0,1,0,Ride,NaN,NaN
14,2,0,Gold Coast,Australia,0,2,M,QLD,1,NaN,...,[-27.96 153.39],153.39,NaN,(GMT+10:00) Australia/Brisbane,56.4,0,0,Ride,NaN,0.0
15,8,0,Huelva,Spain,0,2,M,Andalucía,1,NaN,...,[37.27 -6.94],-6.94,NaN,(GMT+01:00) Europe/Madrid,384.7,0,0,Ride,NaN,NaN
16,0,0,Perth,Australia,0,2,M,WA,1,NaN,...,NaN,NaN,NaN,(GMT+08:00) Australia/Perth,0.0,0,0,Run,NaN,0.0
17,0,0,Faversham,United Kingdom,0,2,M,Kent,1,NaN,...,[51.33 0.87],0.87,NaN,(GMT+00:00) Europe/London,241.8,0,0,Ride,NaN,NaN
18,8,0,Bendigo,Australia,0,2,M,VIC,11,84.1,...,[-36.78 144.32],144.32,NaN,(GMT+10:00) Australia/Melbourne,383.8,0,0,Ride,NaN,NaN
19,0,0,Ogden,United States,0,2,M,UT,1,NaN,...,NaN,NaN,NaN,(GMT-07:00) America/Denver,0.0,0,0,Ride,NaN,0.0
20,1,0,Madison,United States,0,2,M,Wisconsin,1,NaN,...,[43.43 -89.71],-89.71,NaN,(GMT-06:00) America/Chicago,810.4,0,0,Run,NaN,2.0
24,0,1,Tempe,United States,1,2,M,AZ,1,79.7,...,[33.4 -111.93],-111.93,44.0,(GMT-07:00) America/Phoenix,103.8,0,0,Ride,NaN,NaN
25,2,0,Alexandria,United States,0,2,M,VA,1,80.1,...,[38.72 -77.17],-77.17,NaN,(GMT-05:00) America/New_York,19.0,0,0,Run,NaN,0.0
26,17,0,Birmingham,United Kingdom,0,2,M,England,1,NaN,...,[52.41 -1.87],-1.87,NaN,(GMT+00:00) Europe/London,258.9,0,0,Ride,NaN,NaN
28,13,0,Girona,Spain,0,2,M,Catalonia,1,NaN,...,[42 2.83],2.83,NaN,(GMT+01:00) Europe/Madrid,1224.2,0,0,Ride,NaN,NaN
29,4,0,Leganés,España,0,2,M,Comunidad de Madrid,1,NaN,...,[40.32 -3.77],-3.77,NaN,(GMT+01:00) Europe/Madrid,449.0,0,0,Ride,NaN,NaN
32,0,1,Oxford,United Kingdom,1,2,M,England,1,NaN,...,[51.64 -1.51],-1.51,NaN,(GMT+00:00) Europe/London,0.0,0,0,Ride,NaN,NaN
33,0,0,Dubuque,United States,0,2,M,IA,1,NaN,...,[42.48 -90.66],-90.66,NaN,(GMT-06:00) America/Chicago,359.0,0,0,Ride,NaN,0.0
34,0,0,Santa Bárbara de Goiás,Brazil,0,2,M,Goiás,5,NaN,...,[-16.58 -49.7],-49.70,NaN,(GMT-03:00) America/Sao_Paulo,399.5,0,0,Ride,NaN,NaN
36,2,0,Cossington,United Kingdom,0,2,M,England,1,79.1,...,[51.16 -2.92],-2.92,NaN,(GMT+00:00) Europe/London,247.0,0,0,Ride,184.0,NaN
42,15,0,Solihull,United Kingdom,0,2,M,West Midlands,1,NaN,...,[52.44 -1.65],-1.65,NaN,(GMT+00:00) Europe/London,253.9,0,0,Ride,NaN,0.0
43,0,1,ตำบล กุดป่อง,ประเทศไทย,1,2,M,เลย,2,70.5,...,[17.49 101.73],101.73,66.0,(GMT+07:00) Asia/Bangkok,1298.0,0,0,Ride,146.0,NaN
47,8,0,NaN,Canada,0,2,M,British Columbia,1,NaN,...,[49.32 -122.96],-122.96,NaN,(GMT-08:00) America/Vancouver,226.2,0,0,Run,NaN,0.0
50,0,0,Perth,Australia,0,2,M,Western Australia,1,NaN,...,NaN,NaN,NaN,(GMT-08:00) America/Los_Angeles,0.0,1,0,Run,NaN,0.0
51,3,0,Hot Springs,United States,0,2,M,AR,1,NaN,...,[33.83 -118.39],-118.39,NaN,(GMT-08:00) America/Los_Angeles,31.4,0,0,Run,NaN,0.0
53,135,1,Surrey,United Kingdom,1,2,M,England,2,NaN,...,[51.39 -0.74],-0.74,NaN,(GMT+00:00) Europe/London,264.9,0,0,Ride,NaN,0.0
55,3,1,Oxford,United Kingdom,1,2,M,Oxfordshire,1,NaN,...,[51.78 -1.26],-1.26,NaN,(GMT+00:00) Europe/London,65.4,0,0,Run,NaN,NaN
56,6,0,Florianópolis,Brasil,0,2,M,Santa Catarina,1,NaN,...,[-27.61 -48.64],-48.64,NaN,(GMT-03:00) America/Sao_Paulo,1762.8,0,0,Ride,NaN,NaN
59,1,0,Vitoria-Gasteiz,Spain,0,2,M,Alava,1,81.8,...,[42.86 -2.66],-2.66,NaN,(GMT+01:00) Europe/Madrid,69.4,0,0,Run,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8043,0,1,Atibaia,Brasil,1,2,M,SP,1,60.3,...,[-23.13 -46.55],-46.55,NaN,(GMT-03:00) America/Sao_Paulo,74.5,0,0,Run,NaN,NaN
8044,0,0,Huez,France,0,2,M,Rhône-Alpes,1,NaN,...,[51.49 -0.15],-0.15,NaN,(GMT+00:00) Europe/London,21.0,0,0,Ride,NaN,NaN
8045,1,0,Rottenbuch,Deutschland,0,2,M,Bayern,1,56.6,...,[47.57 11.08],11.08,NaN,(GMT+01:00) Europe/Berlin,1428.0,0,0,Run,NaN,NaN
8046,1,1,Zürich,Switzerland,1,2,M,Zürich,1,84.1,...,[47.36 8.52],8.52,65.0,(GMT+01:00) Europe/Zurich,129.4,0,0,Run,NaN,3.0
8047,0,0,Saint Petersburg,Russia,0,2,M,Saint Petersburg,1,NaN,...,[64.55 40.53],40.53,NaN,(GMT+03:00) Europe/Moscow,10.8,0,0,Ride,NaN,0.0
8048,0,1,Weston,United States,1,2,M,FL,8,NaN,...,[26.07 -80.38],-80.38,NaN,(GMT-05:00) America/New_York,0.0,0,0,Ride,NaN,NaN
8049,17,0,Warrington,United Kingdom,0,2,M,England,1,NaN,...,[53.48 -2.5],-2.50,NaN,(GMT+00:00) Europe/London,112.1,0,0,Ride,NaN,0.0
8050,0,0,Shamokin,United States,0,2,M,PA,1,NaN,...,[40.79 -76.56],-76.56,NaN,(GMT-05:00) America/New_York,0.0,0,0,Walk,NaN,NaN
8051,1,0,Antipolo,Philippines,0,2,M,Calabarzon,1,NaN,...,[14.61 121.12],121.12,NaN,(GMT+08:00) Asia/Manila,0.0,0,0,Run,NaN,0.0
8052,4,0,Loughborough,United Kingdom,0,2,M,England,2,67.9,...,[53.36 -1.81],-1.81,NaN,(GMT+00:00) Europe/London,846.0,0,0,Ride,157.0,NaN
8053,0,0,Magna,United States,0,2,M,UT,1,NaN,...,[40.69 -112.1],-112.10,NaN,(GMT-07:00) America/Denver,68.8,0,0,Run,NaN,0.0
8055,1,0,Linnei Township,Taiwan,0,2,M,NaN,1,NaN,...,[23.83 120.78],120.78,NaN,(GMT+08:00) Asia/Taipei,27.9,0,0,Run,NaN,0.0
8057,12,1,Orpington,United Kingdom,1,2,M,England,1,NaN,...,[51.39 0.1],0.10,NaN,(GMT+00:00) Europe/London,287.7,0,0,Ride,NaN,0.0
8058,15,0,Coventry,United Kingdom,0,2,M,England,1,NaN,...,[52.38 -1.55],-1.55,NaN,(GMT+00:00) Europe/London,132.5,0,0,Ride,NaN,0.0
8061,0,0,Bristol,United Kingdom,0,2,M,England,1,NaN,...,[51.5 -2.55],-2.55,NaN,(GMT+00:00) Europe/London,11.4,0,0,Ride,NaN,0.0
8062,6,0,Aarle Rixtel,Nederland,0,2,M,NB,4,90.6,...,[51.51 5.63],5.63,NaN,(GMT+01:00) Europe/Amsterdam,99.0,0,0,Ride,NaN,NaN
8064,3,1,Firenze,Italia,1,2,M,Toscana,1,NaN,...,[43.79 11.27],11.27,NaN,(GMT+01:00) Europe/Rome,625.0,0,0,Ride,NaN,NaN
8069,1,0,Lincoln,United States,0,2,M,NE,1,76.4,...,[40.81 -96.69],-96.69,NaN,(GMT-06:00) America/Chicago,762.8,0,0,Ride,167.0,NaN
8074,0,0,Stiens,The Netherlands,0,2,M,FR,1,NaN,...,[53.22 5.77],5.77,NaN,(GMT+01:00) Europe/Amsterdam,0.0,0,0,Run,NaN,NaN
8075,6,0,Brooklyn Park,Australia,0,2,M,SA,1,NaN,...,[-34.93 138.54],138.54,NaN,(GMT+09:30) Australia/Adelaide,66.3,0,0,Ride,NaN,0.0
8076,0,0,Dubai,United Arab Emirates,0,2,M,Dubai,1,NaN,...,[25.06 55.16],55.16,NaN,(GMT+04:00) Asia/Dubai,21.4,0,0,Run,NaN,NaN
8077,0,0,Oviedo,España,0,2,M,ASTURIAS,1,88.6,...,[43.38 -5.81],-5.81,NaN,(GMT+01:00) Europe/Madrid,2.0,0,0,Ride,NaN,NaN
8078,0,0,Canberra,Australia,0,2,M,ACT,2,82.7,...,[-33.4 151.38],151.38,NaN,(GMT+10:00) Australia/Sydney,221.0,0,0,Run,NaN,NaN
8079,1,0,Halifax,United Kingdom,0,2,M,England,1,NaN,...,[53.7 -1.9],-1.90,NaN,(GMT+00:00) Europe/London,13.6,0,0,Ride,NaN,NaN
8080,0,0,Santa Maria Da Feira,Portugal,0,2,M,Aveiro District,1,NaN,...,[40.96 -8.55],-8.55,NaN,(GMT+00:00) Europe/Lisbon,34.2,0,0,Run,NaN,0.0
8081,8,1,Kaitaia,New Zealand,1,2,M,Northland,2,59.1,...,[-35.11 173.26],173.26,62.0,(GMT+12:00) Pacific/Auckland,451.0,0,0,Ride,NaN,NaN
8082,7,1,Alphington,Australia,1,2,M,VIC,2,72.5,...,[-37.78 145.03],145.03,50.0,(GMT+10:00) Australia/Melbourne,549.6,0,0,Ride,NaN,NaN
8086,0,0,Sugarloaf,United States,0,2,M,PA,1,NaN,...,NaN,NaN,NaN,(GMT-05:00) America/New_York,0.0,0,0,Run,NaN,0.0
8091,5,0,Marham,United Kingdom,0,2,M,NORFOLK,1,NaN,...,[52.34 0.78],0.78,NaN,(GMT+00:00) Europe/London,12.5,0,0,Run,NaN,0.0
8092,0,0,Parañaque,Philippines,0,2,M,Metro Manila,1,NaN,...,[14.48 120.99],120.99,NaN,(GMT+08:00) Asia/Manila,0.0,0,0,Ride,NaN,0.0